name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo_mysql
          tools: composer:v2

      - name: Install PHP Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate App Key
        run: php artisan key:generate
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build
